language: node_js
node_js: stable
sudo: required
cache:
  directories:
    - node_modules

branches:
  only:
  - source

before_install:
- npm install -g hexo-cli

install:
- npm install
- npm install hexo-deployer-git --save

script:
- hexo clean
- hexo generate

after_script:
- git config --global user.name "invom"
- git config --global user.email "invom@qq.com"
- sed -i "s/gh_token/${GIT_TOKEN}/g" ./_config.yml
- hexo deploy