#---------------------------
# Material-T
# Author: invom
# Github: https://github.com/invom/Material-T
#---------------------------

#---------------------------
# 全局
# Site
#---------------------------
favicon: /favicon.ico
apple_touch_icon: /apple-touch-icon.png


#---------------------------
# 首页
# Index Page
#---------------------------
index: 
  subtitle:
    enable: true
  head_img: /img/index-head.jpg

#---------------------------
# 导航栏
# Head Navbar
#---------------------------
navbar:
  menu:
    enable: true
    list:
      archives: /archives/
      about: /about/
  icons:
    enable: true
    tips: 'See me here'
    list: 
      github: https://github.com/invom
      twitter: https://twitter.com/faultymach1ne
  

#---------------------------
# 文章页
# Post Page
#---------------------------
post: 
  head_img: /img/post-head.jpg
  comments_type: 'disqus'
  disqus: 
    shortname: invomblog
  toc: 
    enable: true

# Code Highlight
# Theme available: github | tomorrow | tomorrow-night | tomorrow-night-eighties
highlight:
  enable: true
  theme: tomorrow-night-eighties


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive: 
  head_img: /img/archive-head.jpg

#---------------------------
# 关于页
# About Page
#---------------------------
about:
  head_img: /img/about-head.jpg
  avatar: /img/avatar.jpg 
  name: invom
  job: Student
  introduce: 安全萌新/bug制造者/小米农
  extension: 
  icons: 
    github: https://github.com/invom
    twitter: https://twitter.com/faultymach1ne


#---------------------------
# 底部信息
# Footer
#---------------------------
footer: <b>多喝热水</b>
